# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Lingua-TypoGenerator
version:      0.01
version_from: lib/Lingua/TypoGenerator.pm
installdirs:  site
requires:
    Test::Simple:                  0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
